version: '3.8'
services:
  localstack:
    image: localstack/localstack-full
    container_name: localstack
    ports:
      - "4566:4566" # use in cloud URL
      - "8055:8080"
    environment:
      - SERVICES=s3,sqs,dynamodb
      - DEFAULT_REGION=eu-central-1
      - DATA_DIR=/tmp/localstack/data
      - START_WEB=1
      - PORT_WEB_UI=8080
      - LAMBDA_EXECUTOR=local
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "~/docker_compose/localstack:/var/lib/localstack"
      - "~/docker_compose/localstack/tmp:/tmp/localstack/data"