AWSTemplateFormatVersion: 2010-09-09
Description: Create an IAM user.

Resources:
  TutorialGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: TutorialGroup

  AwsTutorialUsername:
    Type: AWS::IAM::User
    Properties:
      UserName: AwsTutorialUsername
      Groups:
        - TutorialGroup

  AwsTutorialUsernameAccessKey:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref AwsTutorialUsername

Outputs:
  outputName:
    Description: Tutorial group name
    Value: !Ref TutorialGroup
  outputARN:
    Description: Tutorial group ARN
    Value: !GetAtt TutorialGroup.Arn
  AccessKeyID:
    Value: !Ref AwsTutorialUsernameAccessKey
  SecretAccessKey:
    Value: !GetAtt AwsTutorialUsernameAccessKey.SecretAccessKey
  User:
    Value: !Ref AwsTutorialUsername